id: lidarr
name: Lidarr
description: Music management
category: arr
web_path: /lidarr/
requires_account_password: true
detection:
  paths:
    - /opt/Lidarr/Lidarr
  systemd_user_units:
    - "lidarr@{user}.service"
