id: prowlarr
name: Prowlarr
description: Indexer manager
category: arr
web_path: /prowlarr/
requires_account_password: true
detection:
  paths:
    - /opt/Prowlarr/Prowlarr
  systemd_user_units:
    - "prowlarr@{user}.service"
