---
- name: Validate nginx site role variables
  ansible.builtin.assert:
    that:
      - brrewery_app_id | length > 0
    fail_msg: brrewery_nginx_site remove requires brrewery_app_id

- name: Remove app nginx location
  ansible.builtin.file:
    path: "{{ brrewery_nginx_apps_dir }}/{{ brrewery_app_id }}.conf"
    state: absent
  notify: Reload nginx
