id: radarr
name: Radarr
description: Movie management
category: arr
web_path: /radarr/
requires_account_password: true
detection:
  paths:
    - /opt/Radarr/Radarr
  systemd_user_units:
    - "radarr@{user}.service"
